import type { Metadata } from 'next';
import { Inter_Tight } from 'next/font/google';
import './globals.scss';
import { TaskProvider } from './context/TaskContext';

const interTight = Inter_Tight({ subsets: ['latin'], weight: ['400', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <TaskProvider>
          {children}
          {modal}
        </TaskProvider>
      </body>
    </html>
  );
}
